project:
  type: website

website:
  title: "E155 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
   ##   - href: blog.qmd
    ##    text: Blog
      - href: labs/labs.qmd
        text: Labs
      - href: project.qmd
        text: Project
      - href: labs/ai/ai.qmd
        text: AI Prototypes
      - href: resources.qmd
        text: Resources

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



